export const LOCAL_TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    menu_title: "Menu",
    cuisine: "CUISINE",
    bar: "BAR",
    breakfast: "Breakfast",
    salads_appetizers: "Salads & Appetizers",
    soups: "Soups",
    second_courses: "Main Courses",
    side_dishes: "Side Dishes",
    desserts: "Desserts",
    bitter_vermut: "Bitters & Vermouth",
    aperitive_digestive: "Aperitifs & Digestifs",
    champagne_sparkling_wine: "Champagne & Sparkling Wine",
    wine: "Wine",
    vodka: "Vodka",
    whisky: "Whisky",
    rum: "Rum",
    beer: "Beer",
    tequila: "Tequila",
    gin: "Gin",
    brandy_cognac: "Brandy & Cognac",
    liqueur: "Liqueur",
    energy_drinks: "Energy Drinks",
    soft_drinks: "Soft Drinks",
    coffee: "Hot Drinks",
    tea: "Tea",
    snacks: "Snacks",
    menu: "Menu",

    omlette: "Omelette",
    oatmeal_with_fresh_fruits: "Oatmeal with fresh fruits",
    pancakes_with_red_caviar: "Pancakes with red caviar",
    pancakes_with_slightly_salted_salmon: "Pancakes with lightly salted salmon",
    bread_and_butter_with_red_caviar: "Bread and butter with red caviar",
    bread_and_butter_with_salmon: "Bread and butter with salmon",

    cesar_salad_with_shrimps: "Caesar salad with shrimps",
    cesar_salad_with_chicken: "Caesar salad with chicken",
    salmon_carpaccio: "Salmon carpaccio",
    veal_carpaccio: "Veal carpaccio",
    greek_salad: "Greek salad",

    zama: "Zama (Traditional Chicken Soup)",

    grilled_salmon_steak: "Grilled salmon steak",
    grilled_dorada: "Grilled Dorada",
    shrimps_with_salsa: "Shrimps with salsa",
    grilled_tiger_prawns: "Grilled tiger prawns",
    chicken_steak: "Chicken steak",
    chick_tabaka: "Chicken Tabaka",
    ribeye_steak: "Ribeye steak",
    rack_of_milk_veal: "Rack of milk veal",
    spaghetti_bolognese: "Spaghetti Bolognese",
    burger: "Burger",
    club_sandwich_with_french_fries: "Club sandwich with French fries",

    rice_with_vegetables: "Rice with vegetables",
    french_fries: "French fries",
    mashed_potatoes: "Mashed potatoes",
    grilled_vegetables: "Grilled vegetables",

    fruit_platter: "Fruit platter",
    cheese_platter: "Cheese platter",
    ice_cream: "Ice cream",
    cake: "Cake",

    campari: "Campari",
    martini_bianco_rosso_extra_dry: "Martini (Bianco, Rosso, Extra Dry)",
    jagermeister: "Jägermeister",

    cricova_cuvee_prestige_brut: "Cricova Cuvee Prestige (Brut)",
    asti_martini_dulce: "Asti Martini (Sweet)",
    foss_marai_prosecco_brut: "Foss Marai Prosecco (Brut)",
    moet_chandon_brut: "Moet & Chandon (Brut)",

    chardonnay: "Chardonnay",
    polifonia_no1: "Polifonia №1",
    rose: "Rosé",
    chardonnay_barrel_fermented: "Chardonnay barrel fermented",
    de_autor_blend_no3: "De Autor Blend №3",
    alb_de_purcari: "Alb de Purcari",
    negru_de_purcari: "Negru de Purcari",
    piccini_pinot: "Piccini Pinot",
    piccini_chianti: "Piccini Chianti",
    mukuzani: "Mukuzani",
    tsinandali: "Tsinandali",

    hortita: "Hortita",
    absolut: "Absolut",
    finlandia: "Finlandia",
    grey_goose: "Grey Goose",

    glenmorange: "Glenmorangie",
    jw_red_label: "J.W. Red Label",
    jw_black_label: "J.W. Black Label",
    jameson: "Jameson",
    jack_daniels: "Jack Daniels",
    chivas_regal_12_yo: "Chivas Regal 12 YO",
    macallan_12_yo: "Macallan 12 YO",

    bacardi: "Bacardi",

    chisinau_blonda: "Chișinău Blondă",
    heineken: "Heineken",
    krombacher_zero: "Krombacher 0",
    birra_moretti_zero: "Birra Moretti Zero",
    krombacher: "Krombacher",

    sauza_gold_silver: "Sauza (Gold, Silver)",
    volcan: "Volcan",

    beefeater: "Beefeater",
    gordons: "Gordon's",

    alcoholic_cocktails: "Alcoholic Cocktails",
    mohito: "Mojito",
    aperol_sprit: "Aperol Spritz",
    djin_tonic: "Gin & Tonic",

    surpriznii_10_yo: "Surpriznii 10 YO",
    kvint_xo_14_yo: "Kvint XO 14 YO",
    hennessy_vsop: "Hennessy VSOP",
    hennessy_xo: "Hennessy XO",

    kahlua: "Kahlua",
    baileys: "Baileys",
    sambuca: "Sambuca",
    cointreau: "Cointreau",

    tiger: "Tiger",
    red_bull: "Red Bull",

    cola_cola: "Coca-Cola",
    schweppes: "Schweppes",
    bucovina: "Bucovina",
    norda: "Norda",
    fresh_juices: "Fresh Juices",
    lemonade: "Lemonade",

    evian: "Evian",
    borjomi: "Borjomi",

    espresso: "Espresso",
    cappucino: "Cappuccino",
    latte: "Latte",

    assorted_tea_ronnefeldt: "Assorted Tea Ronnefeldt",

    nuts: "Nuts",
    pistachios: "Pistachios",
    ciocolata_bucuria: 'Chocolate "Bucuria"',
  },
  he: {
    menu_title: "תפריט",
    cuisine: "מטבח",
    bar: "בר",
    breakfast: "ארוחת בוקר",
    salads_appetizers: "סלטים ומנות פתיחה",
    soups: "מרקים",
    second_courses: "מנות עיקריות",
    side_dishes: "תוספות",
    desserts: "קינוחים",
    bitter_vermut: "ביטר וורמוט",
    aperitive_digestive: "אפריטיף ודיז'סטיף",
    champagne_sparkling_wine: "שמפניה ויין מבעבע",
    wine: "יין",
    vodka: "וודקה",
    whisky: "וויסקי",
    rum: "רום",
    beer: "בירה",
    tequila: "טקילה",
    gin: "ג'ין",
    brandy_cognac: "ברנדי וקוניאק",
    liqueur: "ליקר",
    energy_drinks: "משקאות אנרגיה",
    soft_drinks: "משקאות קלים",
    coffee: "משקאות חמים",
    tea: "תה",
    snacks: "חטיפים",
    menu: "תפריט",

    omlette: "חביתה",
    oatmeal_with_fresh_fruits: "דייסת שיבולת שועל עם פירות טריים",
    pancakes_with_red_caviar: "פנקייק עם קוויאר אדום",
    pancakes_with_slightly_salted_salmon: "פנקייק עם סלמון במליחות מעודנת",
    bread_and_butter_with_red_caviar: "לחם עם חמאה וקוויאר אדום",
    bread_and_butter_with_salmon: "לחם עם חמאה וסלמון",

    cesar_salad_with_shrimps: "סלט קיסר עם שרימפס",
    cesar_salad_with_chicken: "סלט קיסר עם עוף",
    salmon_carpaccio: "קרפצ'יו סלמון",
    veal_carpaccio: "קרפצ'יו עגל",
    greek_salad: "סלט יווני",

    zama: "זאמה (מרק עוף מסורתי)",

    grilled_salmon_steak: "סטייק סלמון בגריל",
    grilled_dorada: "דניס (דוראדו) בגריל",
    shrimps_with_salsa: "שרימפס עם סלסה",
    grilled_tiger_prawns: "שרימפס טייגר בגריל",
    chicken_steak: "סטייק עוף",
    chick_tabaka: "עוף טבקא",
    ribeye_steak: "סטייק אנטריקוט",
    rack_of_milk_veal: "צלעות עגל חלב",
    spaghetti_bolognese: "ספגטי בולונז",
    burger: "בורגר",
    club_sandwich_with_french_fries: "קלאב סנדוויץ' עם צ'יפס",

    rice_with_vegetables: "אורז עם ירקות",
    french_fries: "צ'יפס",
    mashed_potatoes: "פירה תפוחי אדמה",
    grilled_vegetables: "ירקות בגריל",

    fruit_platter: "צלחת פירות",
    cheese_platter: "פלטת גבינות",
    ice_cream: "גלידה",
    cake: "עוגה",

    campari: "Campari",
    martini_bianco_rosso_extra_dry: "Martini (Bianco, Rosso, Extra Dry)",
    jagermeister: "Jägermeister",

    cricova_cuvee_prestige_brut: "Cricova Cuvee Prestige (Brut)",
    asti_martini_dulce: "Asti Martini (מתוק)",
    foss_marai_prosecco_brut: "Foss Marai Prosecco (Brut)",
    moet_chandon_brut: "Moet & Chandon (Brut)",

    chardonnay: "Chardonnay",
    polifonia_no1: "Polifonia №1",
    rose: "רוזה",
    chardonnay_barrel_fermented: "Chardonnay מיושן בחבית",
    de_autor_blend_no3: "De Autor Blend №3",
    alb_de_purcari: "Alb de Purcari",
    negru_de_purcari: "Negru de Purcari",
    piccini_pinot: "Piccini Pinot",
    piccini_chianti: "Piccini Chianti",
    mukuzani: "Mukuzani",
    tsinandali: "Tsinandali",

    hortita: "Hortita",
    absolut: "Absolut",
    finlandia: "Finlandia",
    grey_goose: "Grey Goose",

    glenmorange: "Glenmorangie",
    jw_red_label: "J.W. Red Label",
    jw_black_label: "J.W. Black Label",
    jameson: "Jameson",
    jack_daniels: "Jack Daniels",
    chivas_regal_12_yo: "Chivas Regal 12 שנים",
    macallan_12_yo: "Macallan 12 שנים",

    bacardi: "Bacardi",

    chisinau_blonda: "Chișinău Blondă",
    heineken: "Heineken",
    krombacher_zero: "Krombacher 0",
    birra_moretti_zero: "Birra Moretti Zero",
    krombacher: "Krombacher",

    sauza_gold_silver: "Sauza (Gold, Silver)",
    volcan: "Volcan",

    beefeater: "Beefeater",
    gordons: "Gordon's",

    alcoholic_cocktails: "קוקטיילים אלכוהוליים",
    mohito: "מוחיטו",
    aperol_sprit: "אפרול שפריץ",
    djin_tonic: "ג'ין טוניק",

    surpriznii_10_yo: "Surpriznii 10 שנים",
    kvint_xo_14_yo: "Kvint XO 14 שנים",
    hennessy_vsop: "Hennessy VSOP",
    hennessy_xo: "Hennessy XO",

    kahlua: "Kahlua",
    baileys: "Baileys",
    sambuca: "Sambuca",
    cointreau: "Cointreau",

    tiger: "Tiger",
    red_bull: "Red Bull",

    cola_cola: "Coca-Cola",
    schweppes: "Schweppes",
    bucovina: "Bucovina",
    norda: "Norda",
    fresh_juices: "מיצים טבעיים",
    lemonade: "לימונדת",

    evian: "Evian",
    borjomi: "בורז'ומי",

    espresso: "אספרסו",
    cappucino: "קפוצ'ינו",
    latte: "לאטה",

    assorted_tea_ronnefeldt: "מבחר תה Ronnefeldt",

    nuts: "אגוזים",
    pistachios: "פיסטוקים",
    ciocolata_bucuria: 'שוקולד "Bucuria"',
  },
  tr: {
    menu_title: "Menü",
    cuisine: "MUTFAK",
    bar: "BAR",
    breakfast: "Kahvaltı",
    salads_appetizers: "Salatalar ve Mezeler",
    soups: "Çorbalar",
    second_courses: "Ana Yemekler",
    side_dishes: "Garnitürler",
    desserts: "Tatlılar",
    bitter_vermut: "Bitterler ve Vermut",
    aperitive_digestive: "Aperatifler ve Dijestifler",
    champagne_sparkling_wine: "Şampanya ve Köpüklü Şarap",
    wine: "Şarap",
    vodka: "Votka",
    whisky: "Viski",
    rum: "Rom",
    beer: "Bira",
    tequila: "Tekila",
    gin: "Cin",
    brandy_cognac: "Brendi ve Konyak",
    liqueur: "Likör",
    energy_drinks: "Enerji İçecekleri",
    soft_drinks: "Alkolsüz İçecekler",
    coffee: "Sıcak İçecekler",
    tea: "Çay",
    snacks: "Atıştırmalıklar",
    menu: "Menü",

    omlette: "Omlet",
    oatmeal_with_fresh_fruits: "Taze meyveli yulaf ezmesi",
    pancakes_with_red_caviar: "Kırmızı havyarlı krep",
    pancakes_with_slightly_salted_salmon: "Hafif tuzlu somonlu krep",
    bread_and_butter_with_red_caviar: "Tereyağlı ve kırmızı havyarlı ekmek",
    bread_and_butter_with_salmon: "Tereyağlı ve somonlu ekmek",

    cesar_salad_with_shrimps: "Karidesli Sezar salatası",
    cesar_salad_with_chicken: "Tavuklu Sezar salatası",
    salmon_carpaccio: "Somon karpaçyo",
    veal_carpaccio: "Dana eti karpaçyo",
    greek_salad: "Yunan salatası",

    zama: "Zama (Geleneksel Tavuk Çorbası)",

    grilled_salmon_steak: "Izgara somon bifteği",
    grilled_dorada: "Izgara çipura (Dorada)",
    shrimps_with_salsa: "Salsa soslu karides",
    grilled_tiger_prawns: "Izgara kaplan karidesi",
    chicken_steak: "Tavuk biftek",
    chick_tabaka: "Tavuk tabaka",
    ribeye_steak: "Antrikot (Ribeye) steak",
    rack_of_milk_veal: "Süt danası pirzolası",
    spaghetti_bolognese: "Spagetti Bolonez",
    burger: "Burger",
    club_sandwich_with_french_fries: "Patates kızartması ile kulüp sandviç",

    rice_with_vegetables: "Sebzeli pilav",
    french_fries: "Patates kızartması",
    mashed_potatoes: "Patates püresi",
    grilled_vegetables: "Izgara sebzeler",

    fruit_platter: "Meyve tabağı",
    cheese_platter: "Peynir tabağı",
    ice_cream: "Dondurma",
    cake: "Pasta",

    campari: "Campari",
    martini_bianco_rosso_extra_dry: "Martini (Bianco, Rosso, Extra Dry)",
    jagermeister: "Jägermeister",

    cricova_cuvee_prestige_brut: "Cricova Cuvee Prestige (Brut)",
    asti_martini_dulce: "Ati Martini (Tatlı)",
    foss_marai_prosecco_brut: "Foss Marai Prosecco (Brut)",
    moet_chandon_brut: "Moet & Chandon (Brut)",

    chardonnay: "Chardonnay",
    polifonia_no1: "Polifonia №1",
    rose: "Roze",
    chardonnay_barrel_fermented: "Meşe fıçıda dinlendirilmiş Chardonnay",
    de_autor_blend_no3: "De Autor Blend №3",
    alb_de_purcari: "Alb de Purcari",
    negru_de_purcari: "Negru de Purcari",
    piccini_pinot: "Piccini Pinot",
    piccini_chianti: "Piccini Chianti",
    mukuzani: "Mukuzani",
    tsinandali: "Tsinandali",

    hortita: "Hortita",
    absolut: "Absolut",
    finlandia: "Finlandia",
    grey_goose: "Grey Goose",

    glenmorange: "Glenmorangie",
    jw_red_label: "J.W. Red Label",
    jw_black_label: "J.W. Black Label",
    jameson: "Jameson",
    jack_daniels: "Jack Daniels",
    chivas_regal_12_yo: "Chivas Regal 12 Yıl",
    macallan_12_yo: "Macallan 12 Yıl",

    bacardi: "Bacardi",

    chisinau_blonda: "Chișinău Blondă",
    heineken: "Heineken",
    krombacher_zero: "Krombacher 0",
    birra_moretti_zero: "Birra Moretti Zero",
    krombacher: "Krombacher",

    sauza_gold_silver: "Sauza (Gold, Silver)",
    volcan: "Volcan",

    beefeater: "Beefeater",
    gordons: "Gordon's",

    alcoholic_cocktails: "Alkollü Kokteyller",
    mohito: "Mojito",
    aperol_sprit: "Aperol Spritz",
    djin_tonic: "Cin Tonik",

    surpriznii_10_yo: "Surpriznii 10 Yıl",
    kvint_xo_14_yo: "Kvint XO 14 Yıl",
    hennessy_vsop: "Hennessy VSOP",
    hennessy_xo: "Hennessy XO",

    kahlua: "Kahlua",
    baileys: "Baileys",
    sambuca: "Sambuca",
    cointreau: "Cointreau",

    tiger: "Tiger",
    red_bull: "Red Bull",

    cola_cola: "Coca-Cola",
    schweppes: "Schweppes",
    bucovina: "Bucovina",
    norda: "Norda",
    fresh_juices: "Taze Sıkılmış Meyve Suları",
    lemonade: "Limonata",

    evian: "Evian",
    borjomi: "Borjomi",

    espresso: "Espresso",
    cappucino: "Cappuccino",
    latte: "Latte",

    assorted_tea_ronnefeldt: "Ronnefeldt Çay Çeşitleri",

    nuts: "Kuruyemiş",
    pistachios: "Antep Fıstığı",
    ciocolata_bucuria: '"Bucuria" Çikolatası',
  },
};
