import {
  AO_REPORT_MAIN_ROUTE,
  ARCHIVE_MAIN_ROUTE,
  CASH_MAIN_ROUTE,
  EMPLOYEES_MAIN_ROUTE,
  FIN_CASH_MAIN_ROUTE,
  INFO_MAIN_ROUTE,
  ORDERS_MAIN_ROUTE,
  REPORTS_BAR_ROUTE,
  REPORTS_CUCINA_ROUTE,
  RESULT_MAIN_ROUTE,
  SCHEDULE_MAIN_ROUTE,
  SETTING_MAIN_ROUTE,
  TIPS_MAIN_ROUTE,
  TTN_MAIN_ROUTE,
} from "@/constants/endpoint-tag";
import {
  Calendar,
  BarChart3,
  List,
  Info,
  Archive,
  DollarSign,
  CreditCard,
  SigmaIcon,
  PersonStandingIcon,
  CalculatorIcon,
  FileTextIcon,
  Settings,
  ClipboardIcon,
} from "lucide-react";

export const SIDEBAR_NAVIGATION = [
  {
    title: SCHEDULE_MAIN_ROUTE,
    url: SCHEDULE_MAIN_ROUTE,
    icon: Calendar,
    setAcces: ["ADMIN", "BAR", "CUCINA", "USER"],
  },
  {
    title: EMPLOYEES_MAIN_ROUTE,
    url: EMPLOYEES_MAIN_ROUTE,
    icon: PersonStandingIcon,
    setAcces: ["ADMIN", "USER"],
  },
  {
    title: REPORTS_BAR_ROUTE,
    url: REPORTS_BAR_ROUTE,
    icon: BarChart3,
    setAcces: ["ADMIN", "BAR", "USER"],
  },
  {
    title: REPORTS_CUCINA_ROUTE,
    url: REPORTS_CUCINA_ROUTE,
    icon: BarChart3,
    setAcces: ["ADMIN", "CUCINA"],
  },

  {
    title: ORDERS_MAIN_ROUTE,
    url: ORDERS_MAIN_ROUTE,
    icon: List,
    setAcces: ["ADMIN", "BAR", "CUCINA"],
  },
  {
    title: INFO_MAIN_ROUTE,
    url: INFO_MAIN_ROUTE,
    icon: Info,
    setAcces: ["ADMIN", "BAR", "CUCINA", "USER"],
  },
  {
    title: ARCHIVE_MAIN_ROUTE,
    url: ARCHIVE_MAIN_ROUTE,
    icon: Archive,
    setAcces: ["ADMIN", "USER"],
  },

  {
    title: TIPS_MAIN_ROUTE,
    url: TIPS_MAIN_ROUTE,
    icon: DollarSign,
    setAcces: ["ADMIN"],
  },
  {
    title: CASH_MAIN_ROUTE,
    url: CASH_MAIN_ROUTE,
    icon: CreditCard,
    setAcces: ["ADMIN", "CASH"],
  },
  {
    title: AO_REPORT_MAIN_ROUTE,
    url: AO_REPORT_MAIN_ROUTE,
    icon: CalculatorIcon,
    setAcces: ["ADMIN"],
  },
  {
    title: TTN_MAIN_ROUTE,
    url: TTN_MAIN_ROUTE,
    icon: FileTextIcon,
    setAcces: ["ADMIN", "FIN"],
  },
  {
    title: FIN_CASH_MAIN_ROUTE,
    url: FIN_CASH_MAIN_ROUTE,
    icon: ClipboardIcon,
    setAcces: ["ADMIN"],
  },
  {
    title: RESULT_MAIN_ROUTE,
    url: RESULT_MAIN_ROUTE,
    icon: SigmaIcon,
    setAcces: ["ADMIN", "MNGR"],
  },
  {
    title: SETTING_MAIN_ROUTE,
    url: SETTING_MAIN_ROUTE,
    icon: Settings,
    setAcces: ["ADMIN"],
  },
];
